.gitignore
README.md
docker-compose.yml

Queremos dockerizar Postgres para no forzar a cada dev a tener una version de postgres en su maquina, que pueda potencialmente generar conflicto de versiones con otros proyectos.

Docker para postgres y update del README

---

README.md

Quedo el README desactualizado tras el ultimo PR de dockerizacion de postgres.

Actualizar README con credenciales de Docker para postgres

---

front/src/App/MyTalks/MyTalks.js
front/src/App/OpenSpace/OpenSpace.js
front/src/shared/MainHeader.js

#2 Mostrar descripcion de Open Space

---

front/src/App/OpenSpace/Talk.js

Al visualizar las charlas vemos que podemos ver el boton "Mas info"
Aca vemos la descripcion y el link a una reunion
Aca vemos unicamente el link porque no hay descripcion

#4 mostrar link en video stream

---

back/src/main/kotlin/com/sos/smartopenspace/controllers/ExceptionHandler.kt
back/src/main/kotlin/com/sos/smartopenspace/controllers/TalkController.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/OpenSpace.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/Talk.kt
back/src/main/kotlin/com/sos/smartopenspace/services/DataService.kt
back/src/main/kotlin/com/sos/smartopenspace/services/TalkService.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/TalkControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/SlotTest.kt
front/src/App/MyTalks/MyTalks.js
front/src/App/MyTalks/Talk/Talk.js
front/src/App/OpenSpace/OpenSpace.js
front/src/helpers/api/os-client.js

- Puede agendar y encolar si el marketplace esta inciado
- Con marketplace sin iniciar solo se puede ver el boton de agendar
- Solo puede agendar una vez que fue encolado. Si el organizador ya agendo su charla no puede encolarse
- Con marketplace sin iniciar no puede agendar ni encolarse pero el organizador puede agendar sus charlas

#8 organizador puede agendar charla siempre

---

front/src/App/Home/OpenSpace.js
front/src/App/Login/Login.js
front/src/App/MyTalks/MyTalks.js
front/src/App/OSProjector/OSProjector.js
front/src/App/OpenSpace/OpenSpace.js
front/src/helpers/routes.js

Ahora al ir a la pantalla de Login desde un Open Space, te redirige automaticamente al Open Space en cuestión al momento del login

Redirigir al os despues de login

---

front/src/App/MyTalks/MyTalks.js

Se agrego la condicion de convocatoria cerrada al boton de cargar charla cuando ya hay charlas cargadas

arreglo de condiciones para visualizacion de botones para cargar charla

---

front/src/shared/MainHeader.js

Se ve muy lindo con el componente de markdown :)

descripcion como markdown

---

back/build.gradle.kts
back/src/main/kotlin/com/sos/smartopenspace/controllers/UserController.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/User.kt
back/src/main/kotlin/com/sos/smartopenspace/services/UserService.kt
back/src/main/resources/db/migration/U1_11__change_password_length.sql
back/src/main/resources/db/migration/V1_11__change_password_length.sql
back/src/test/kotlin/com/sos/smartopenspace/controllers/UserControllerTest.kt
front/src/App/Home/Home.js

Se hashean las contraseñas al registrarse, y loguearse.
Agregamos un boton con un endpoint ppara correrlo en prod y despues borrarlo.

No guardar password en db

---

back/src/main/kotlin/com/sos/smartopenspace/controllers/UserController.kt
back/src/main/kotlin/com/sos/smartopenspace/services/UserService.kt
front/src/App/Home/Home.js

Se borra todo lo que hasheaba la password de los usuarios antiguos en el back y front

Borrando boton de hash

---

back/src/test/kotlin/com/sos/smartopenspace/TestingObjectFactory.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/TalkControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/SlotTest.kt
front/src/App/MyTalks/Talk/SelectSlot.js

- Se arreglo el error que hacia que aveces se eligiera mal la fecha al agendar
- Se agregaron test de modelo para agendado de fecha en otro dia
- Se agregaron aserciones en los test de controller

Arreglo de exchange en multiples fechas

---

back/src/main/kotlin/com/sos/smartopenspace/controllers/UserController.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/User.kt
back/src/main/kotlin/com/sos/smartopenspace/helpers/UserLoginDTO.kt
back/src/main/kotlin/com/sos/smartopenspace/persistence/UserRepository.kt
back/src/main/kotlin/com/sos/smartopenspace/services/UserService.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/UserControllerTest.kt
front/src/App/MyTalks/MyTalks.js
front/src/helpers/useAuth.js

- Se elimino el endpoint identify
- Se oculto el password para que no llegue como respuesta en el front
- Se elimino el boton para que el organizador pueda crear una charla para un orador, ya que habia quedado obsoleto

No devolver usuario en identify

---

front/src/App/MyTalks/Talk/Talk.js
front/src/App/OpenSpace/Talk.js
front/src/App/TalkForm/TalkForm.js

se agrego markdown a la descripcion de la charla

---

front/src/App/OpenSpace/Talk.js
front/src/shared/Title.js

se agrego truncate para cuando el titulo es muy largo

---

front/src/App/MyTalks/Talk/Talk.js
front/src/App/OpenSpace/Talk.js
front/src/App/OpenSpace/Talks.js
front/src/shared/Card.js
front/src/shared/Title.js

- Se saco el elipsis del titulo de la charla
- Ahora las cards se van a adaptar al tamaño de la que tiene el titulo mas grande en esa fila

Arreglo titulo charla

---

front/src/App/OpenSpace/Talks.js

cambios en la vista del slider

---

back/src/main/kotlin/com/sos/smartopenspace/controllers/OpenSpaceController.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/Exceptions.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/User.kt
back/src/main/kotlin/com/sos/smartopenspace/services/OpenSpaceService.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/OpenSpaceControllerTest.kt
front/src/App/Home/Home.js
front/src/App/Home/OpenSpace.js
front/src/helpers/api/os-client.js

Este PR permite eliminar un open space previamente creado
https://www.loom.com/share/0fe3ef3ecc0345f789d6b2f934314532

Delete open space

---

back/.gitignore
front/src/App/Login/Login.js
front/src/shared/MyForm.js

add password confirmation to register

---

back/src/main/kotlin/com/sos/smartopenspace/domain/Room.kt
back/src/main/resources/db/migration/U1_12__add_links_to_rooms.sql
back/src/main/resources/db/migration/V1_12__add_links_to_rooms.sql
front/src/App/EditOpenSpace/Rooms.js
front/src/App/OpenSpace/Talk.js

https://www.loom.com/share/488a752cd3be4189a27083b31872a52f

Add room link

---

back/src/main/kotlin/com/sos/smartopenspace/domain/Talk.kt

Cambio el fetch type del set de documentos de una charla de EAGER a LAZY

change docuemnts to lazy

---

back/build.gradle.kts
back/src/main/kotlin/com/sos/smartopenspace/config/WebConfig.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/OpenSpace.kt
back/src/main/kotlin/com/sos/smartopenspace/helpers/OpenSpaceDTO.kt
front/src/App/EditOpenSpace/NewOpenSpace.js
front/src/App/EditOpenSpace/OpenSpaceForm.js
front/src/App/Header.js
front/src/App/Home/OpenSpace.js
front/src/App/model/openSpace.js

Como un aside de que ahora podemos editar un open space, pensamos que sería lindo poder crear un open space con los mínimos requerimientos. Lo que me imagino es que podés crear un open space y dejar que la gente envie sus propuestas. Dps, de acuerdo a la cantidad de propuestas, pensás en la cantidad de salas/horarios que necesitás y armás tu agenda.

Allow minimum open space

---

back/src/main/kotlin/com/sos/smartopenspace/domain/User.kt
back/src/main/kotlin/com/sos/smartopenspace/services/OpenSpaceService.kt
back/src/test/kotlin/com/sos/smartopenspace/TestingObjectFactory.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/TalkControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/OpenSpaceTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/QueueTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/SlotTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/TalkTest.kt

remuevo un metodo que no estaba haciend nada y ya no se usaba en ningun lugar menos en tests

remove add talk method from user

---

back/src/main/kotlin/com/sos/smartopenspace/domain/OpenSpace.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/Slot.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/OpenSpaceControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/TalkControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/OpenSpaceTest.kt

En este PR se cambia el tipado de date en Slot para que pase de 
LocalDate? -> LocalDate

change slot date type to be mandatory

---

front/src/App/MyTalks/Talk/Talk.js
front/src/App/OpenSpace/Talk.js

Al clickear en una charla en la pagina de mis charlas, ahora se redirige al detalle de dicha charla

Add link to talk in detail in my talks page

---

back/src/main/kotlin/com/sos/smartopenspace/services/EmailService.kt
back/src/main/resources/application.properties

send instead of a simple message, an html message, to fit the url in a text

send html mail

---

front/src/App/MyTalks/Talk/Talk.js

cuadno te deslogueas en esta pantalla tira un erro antes de volver a la pantalla de login
Este error se debia a que conseguia el id del usuario y este paso a ser undefined
Asi que ahora primero se chequea que el usuairo exista antes de pedirle el id

check user exists

---

back/src/main/kotlin/com/sos/smartopenspace/controllers/OpenSpaceController.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/Exceptions.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/OpenSpace.kt
back/src/main/kotlin/com/sos/smartopenspace/domain/Review.kt
back/src/main/kotlin/com/sos/smartopenspace/dto/request/CreateReviewRequestDTO.kt
back/src/main/kotlin/com/sos/smartopenspace/services/OpenSpaceService.kt
back/src/main/kotlin/com/sos/smartopenspace/services/TalkService.kt
back/src/main/resources/db/migration/U1_16__create_is_active_voting.sql
back/src/main/resources/db/migration/U1_17__add_show_speaker_to_openspace.sql
back/src/main/resources/db/migration/V1_16__create_is_active_voting.sql
back/src/main/resources/db/migration/V1_17__add_show_speaker_to_openspace.sql
back/src/test/kotlin/com/sos/smartopenspace/controllers/OpenSpaceControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/controllers/TalkControllerTest.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/OpenSpaceTest.kt
front/src/App/MyTalks/Talk/Talk.js
front/src/App/OpenSpace/DisplayTalks.js
front/src/App/OpenSpace/OpenSpace.js
front/src/App/OpenSpace/Talk.js
front/src/App/OpenSpace/TalksGrid.js
front/src/App/OpenSpace/TrackWithTalks.js
front/src/App/OpenSpace/Vote.js
front/src/App/OpenSpace/buttons/ButtonToToggleShowSpeakerName.js
front/src/App/OpenSpace/buttons/ButtonToToggleVoting.js
front/src/App/model/openSpace.js
front/src/helpers/api/os-client.js

https://www.loom.com/share/f54501006630442aababea7c9c25db3c?sid=5ea94df9-217b-49c4-b309-5e57d87364ff
- No mostrar descripcion en mis charlas
- el comentario de la review no es obligatorio
- no se pueden dar 2 reviews
- No pueden votar su propia charla
- Abrir/Cerrar la votación
- Mostrar/No Mostrar speaker

Agiles fix

---

back/src/main/kotlin/com/sos/smartopenspace/domain/Email.kt
back/src/main/kotlin/com/sos/smartopenspace/services/EmailService.kt
back/src/main/kotlin/com/sos/smartopenspace/services/UserService.kt
back/src/main/resources/application-dev.properties

Completa el contenido del mail + agrega una config. para no necesitar variables de ambiente del mailer en local

Mejora mail recupero contrasenia

---

front/src/App/MyTalks/Talk/Talk.js

El administrador puede hacer cualquier cosa, incluso eliminar las charlas de los speakers (pasaba en el Agiles 2024 q gente presentaba charlas, pero no había ido a la conferencia)

El administrador puede eliminar una charla

---

back/src/main/kotlin/com/sos/smartopenspace/domain/OpenSpace.kt
back/src/main/kotlin/com/sos/smartopenspace/persistence/TalkRepository.kt
back/src/main/kotlin/com/sos/smartopenspace/services/OpenSpaceService.kt
back/src/test/kotlin/com/sos/smartopenspace/domain/OpenSpaceTest.kt
front/src/App/OpenSpace/DisplayTalks.js
front/src/App/OpenSpace/Talk.js
front/src/App/OpenSpace/TrackWithTalks.js
front/src/App/TalkForm/TalkForm.js

reference #236 
An open space page crushed if tracks had been created but talks weren't assigned to one.
Solution:
- Enable a talk to not have a track
- When deleting a track the talks associated to it become talks without tracks
Uploading Screen Recording 2024-10-08 at 11.38.22 AM.mov…

Check if talk has track

---

front/src/helpers/useAuth.jsx

Este es un codigo que teniamos y que despues sacamos erroneamente, es para agregar metadata a logrocket (que ahora estariamos retomando su uso)

Logrocket identify

---

front/src/App/DesignSystem/DesignStystem.jsx
front/src/App/components/atom/Button.jsx
front/src/App/components/molecule/AddElementBox.jsx

New Designs - Component - Add Element Box

---

front/src/App/DesignSystem/DesignStystem.jsx
front/src/App/components/atom/DateTimeIndicator.jsx

New Designs - Date Time Indicator

---

front/src/App/DesignSystem/DesignStystem.jsx
front/src/App/components/atom/Button.jsx
front/src/App/components/molecule/Card.jsx
front/src/App/components/molecule/Readme.md
front/src/App/components/molecule/TimeCard.jsx
front/src/shared/icons.jsx

```jsx
<Card title="Título de la Card" color="card-blue" showVotes />
```
```jsx
<Card
title="Título de la Card"
description="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
/>
```
```jsx
<Card
title="Título de la Card"
description="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
color="card-green"
buttons={[
{
icon: HaltIcon,
onClick: () => console.log('Clicked halt in card'),
secondary: true,
blackAndWhite: true,
},
{
icon: EditIcon,
onClick: () => console.log('Clicked edit in card'),
blackAndWhite: true,
},
{
icon: AddIcon,
onClick: () => console.log('Clicked add in card'),
blackAndWhite: true,
},
]}
/>
```
```jsx
<TimeCard
time={{
start: new Date(new Date().setHours(18, 0, 0, 0)),
end: new Date(new Date().setHours(21, 0, 0, 0)),
}}
title="Título de la Card" …
```

New Component - Generic Card

---

front/src/App/DesignSystem/DesignStystem.jsx
front/src/App/components/atom/DateTimePicker.jsx
front/src/App/theme.js

Reference #279 
https://github.com/user-attachments/assets/816a0c33-0cb3-4dec-9d78-66f1d1feb927

New DateTimePicker design in DesignSystem

---

front/src/App/DesignSystem/DesignStystem.jsx
front/src/App/components/atom/DateTimePicker.jsx
front/src/App/components/molecule/DateTimeForm.jsx

Reference #283 
https://github.com/user-attachments/assets/e1eed14a-3ace-4ed4-a0b8-a28277be5044

New Date Time Form

---

front/src/App/OpenSpace/OpenSpace.jsx

Organizador
Participante logueado

El titulo tablero de control debe verlo solamente al organizador del OS

---

front/src/App/Manual/Manual.jsx
front/src/App/OpenSpace/DisplayTalks.jsx
front/src/App/OpenSpace/OpenSpace.jsx
front/src/App/OpenSpace/Talk.jsx
front/src/App/OpenSpace/TalksGrid.jsx
front/src/App/OpenSpace/TrackDropdown.jsx
front/src/App/OpenSpace/TrackWithTalks.jsx
front/src/App/components/atom/Button.jsx
front/src/helpers/api/os-client.js
front/src/helpers/scrollUtils.js
front/src/shared/MainHeader.jsx
front/src/shared/constants.js

Reference #348 
Make tracks and their talks as dropdowns:
https://github.com/user-attachments/assets/d28dc0df-db50-472d-83d6-d371766083a0

New tracks and talks view in principal OS view
